### ISSUE TITLE
#CLOSE_NOTIFICATION# displayed on the tooltip.

### ISSUE THREAD

**Issue by Prze-moC** [Pretius/apex-enhanced-notifications#4]
"#CLOSE_NOTIFICATION#" text is displayed on the tooltip. I guess this was supposed to be a placeholder for a parameter, but the parametr is not there...

**Comment by bostrowski** [comment]
@Prze-moC 
The plug-in was created for APEX 4.1 and 5.1 where developers haven't access to APEX message API. For newer version using apex.message api is recommended.

On what version you trying to implement the plug-in?

**Comment by Prze-moC** [comment]
5.1.4.00.08
I'm using apex.message for alert and confirmations, but it contains only showPageSuccess, so your plug-in fits great here.
Have I missed some parameter?

**Comment by bostrowski** [comment]
OK I think I've understood what you are asking for. I've checked the plug-in at apex.oracle.com (APEX 20.1) and you mean this:

![image](https://user-images.githubusercontent.com/15342508/83361779-29c8dd00-a38c-11ea-9b95-47c7336549e3.png)

The plug-in is pretty old and I'm not sure whether I will prepare new version of it or whether I will be updating current version. 

What you can do about it:
- change the plug-in component setting so it won't use UT template and then remove `#CLOSE_NOTIFICATION#`
![image](https://user-images.githubusercontent.com/15342508/83361814-76acb380-a38c-11ea-9a76-86aa12d4cadc.png)
- modify the plug-in PL/SQL and replace `#CLOSE_NOTIFCATION#` with any string (or Translation text using APEX_LANG API)
- modify the plug-in JavaScript to replace `#CLOSE_NOTIFCATION#` 

Regards
Bartosz

**Comment by Prze-moC** [comment]
Thanks Bartosz,
I've done what you suggested 1. and 2. above. 
3. (modify the plug-in JavaScript) is actually a new version, I guess (too difficult for me).
For the record (for potential other users of your plug-in), I also applied 4. workaround which is to hide the tooltip with JavaScript run after displaying the notification.

Regards, 
Przemek

**Comment by bostrowski** [comment]
Cool, I'm glad it worked for you. I'm closing the thread.
